services:
  web:
    build: .
    ports:
      - "8280:8280"
    volumes:
      - "${PERSIST_DIR}/data:/app/data"
      - "${PERSIST_DIR}/static/images:/app/static/images"
    restart: unless-stopped
